version: '3.4'

services:
  
  jboss:
    depends_on: 
      - oracle
    build: jboss
    image: jboss:ready
    container_name: jboss
    volumes:
      - .:/usr/local/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:8080
      - 9990:9990

  oracle:
    build: oracle
    image: oracle:11-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src 